
INSERT INTO `items` (`name`, `label`, `weight`, `limit`, `rare`, `can_remove`, `description`) VALUES
('WEAPON_ADVANCEDRIFLE', 'Advanced Machine Gun', 4.5, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_APPISTOL', 'Pistol AP', 1.1, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_ASSAULTRIFLE', 'Assault Machine Gun', 4.2, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_ASSAULTSHOTGUN', 'Assault Rifle', 3.5, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_ASSAULTSMG', 'Sub-Assault Machine Gun', 3, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_AUTOSHOTGUN', 'Automatic Shotgun', 3.7, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_BALL', 'Baseball ball', 0.2, 1, 0, 1, ''),
('WEAPON_BAT', 'Baseball bat', 1.5, 1, 0, 1, ''),
('WEAPON_BATTLEAXE', 'Battle Axe', 3, 1, 0, 1, ''),
('WEAPON_BOTTLE', 'Bottle', 1, 1, 0, 1, ''),
('WEAPON_BULLPUPRIFLE', 'Bullpup machine gun', 4.2, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_BULLPUPSHOTGUN', 'Bullpup Shotgun', 3.9, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_BZGAS', 'BZ gas', 1.5, 10, 0, 1, ''),
('WEAPON_CARBINERIFLE', 'Carbine Rifle', 4.3, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_COMBATMG', 'Combat MG', 4.6, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_COMBATPDW', 'Combat PDW', 3.7, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_COMBATPISTOL', 'Combat Pistol', 3, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_COMPACTLAUNCHER', 'Compact Launcher', 2, 1, 0, 1, ''),
('WEAPON_COMPACTRIFLE', 'Compact machine gun', 3.7, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_CROWBAR', 'Crowbar', 0.5, 1, 0, 1, ''),
('WEAPON_DAGGER', 'Dagger', 1.5, 1, 0, 1, ''),
('WEAPON_DBSHOTGUN', 'Double-barreled shotgun', 3.2, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_DIGISCANNER', 'Digiscanner', 1, 1, 0, 1, ''),
('WEAPON_DOUBLEACTION', 'Double-action revolver', 2.8, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_FIREEXTINGUISHER', 'Fire extinguisher', 10, 1, 0, 1, ''),
('WEAPON_FIREWORK', 'Rocket Bazooka', 1, 1, 0, 1, ''),
('WEAPON_FLARE', 'Signaling', 1, 1, 0, 1, ''),
('WEAPON_FLAREGUN', 'Flare Gun', 1.8, 1, 0, 1, ''),
('WEAPON_FLASHLIGHT', 'Flashlight', 1, 1, 0, 1, ''),
('WEAPON_GARBAGEBAG', 'Garbage bag', 1, 1, 0, 1, ''),
('WEAPON_GOLFCLUB', 'Golf Club', 3.3, 1, 0, 1, ''),
('WEAPON_GRENADE', 'Grenade', 0.3, 10, 0, 1, ''),
('WEAPON_GUSENBERG', 'Gusenberg', 2.8, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_HAMMER', 'Hammer', 0.5, 1, 0, 1, ''),
('WEAPON_HANDCUFFS', 'Handcuffs', 0.5, 1, 0, 1, ''),
('WEAPON_HATCHET', 'Axe', 2.5, 1, 0, 1, ''),
('WEAPON_HEAVYPISTOL', 'Heavy pistol', 3.2, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_HEAVYSHOTGUN', 'Heavy shotgun', 4.2, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_HEAVYSNIPER', 'Heavy Sniper', 5.8, 1, 0, 1, 'Uses ammunition type "Sniper"'),
('WEAPON_HOMINGLAUNCHER', 'Guided Bazooka', 1, 1, 0, 1, ''),
('WEAPON_KNIFE', 'Knife', 0.5, 1, 0, 1, ''),
('WEAPON_KNUCKLE', 'Punch-English', 1, 1, 0, 1, ''),
('WEAPON_MACHETE', 'Machete', 1, 1, 0, 1, ''),
('WEAPON_MACHINEPISTOL', 'Machine Gun', 2.8, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_MARKSMANPISTOL', 'Marksman Pistol', 3, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_MARKSMANRIFLE', 'Marksman machine gun', 6, 1, 0, 1, 'Uses ammunition type "Sniper"'),
('WEAPON_MG', 'MG', 4.2, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_MICROSMG', 'Micro SMG', 3.8, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_MINIGUN', 'Minigun', 1, 1, 0, 1, ''),
('WEAPON_MINISMG', 'Mini SMG', 2.5, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_MOLOTOV', 'Molotov cocktail', 1, 1, 0, 1, ''),
('WEAPON_MUSKET', 'Musket', 2.8, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_NIGHTSTICK', 'Police Baton', 1, 1, 0, 1, ''),
('WEAPON_PETROLCAN', 'Gallon of fuel', 3, 1, 0, 1, ''),
('WEAPON_PIPEBOMB', 'Homemade bomb', 1, 1, 0, 1, ''),
('WEAPON_PISTOL', 'Pistol', 2.2, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_PISTOL50', 'Pistol .50', 2.5, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_POOLCUE', 'Billiard cue', 1, 1, 0, 1, ''),
('WEAPON_PROXMINE', 'Proximity mine', 1, 10, 0, 1, ''),
('WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 3.5, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_RAILGUN', 'Rail Gun', 5.2, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_REVOLVER', 'Revolver', 3, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_RPG', 'Bazooka RPG', 8, 1, 0, 1, ''),
('WEAPON_SAWNOFFSHOTGUN', 'Sawn-Off Shotgun', 2.8, 1, 0, 1, 'Uses ammunition type "Shotgun"'),
('WEAPON_SMG', 'SMG', 3.8, 1, 0, 1, 'Uses ammunition type "SMG"'),
('WEAPON_SMOKEGRENADE', 'Smoke stack', 0.5, 10, 0, 1, ''),
('WEAPON_SNIPERRIFLE', 'Sniper machine gun', 6.2, 1, 0, 1, 'Uses ammunition type "Sniper"'),
('WEAPON_SNOWBALL', 'Snowball', 1, 10, 0, 1, ''),
('WEAPON_SNSPISTOL', 'Pistol SNS', 2.4, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_SPECIALCARBINE', 'Special Machine Gun', 3.6, 1, 0, 1, 'Uses ammunition type "Rifle"'),
('WEAPON_STICKYBOMB', 'Pump C4', 2.5, 10, 0, 1, ''),
('WEAPON_STINGER', 'Stinger', 1, 1, 0, 1, ''),
('WEAPON_STUNGUN', 'Electroshock gun', 1, 1, 0, 1, ''),
('WEAPON_SWITCHBLADE', 'Switchblade', 1.6, 1, 0, 1, ''),
('WEAPON_VINTAGEPISTOL', 'Vintage Pistol', 2.4, 1, 0, 1, 'Uses ammunition type "Pistol"'),
('WEAPON_WRENCH', 'Wrench', 2, 1, 0, 1, ''),
('AMMO_PISTOL', 'Pistol ammunition box', 1.5, 100, 0, 1, 'Ammunition box with 30 category bullets "Pistol".'),
('AMMO_PISTOL_LARGE', 'Pistol ammunition pack', 2.7, 100, 0, 1, 'Ammunition pack com 60 category bullets "Pistol".'),
('AMMO_SHOTGUN', 'Shotgun ammo box', 1.35, 100, 0, 1, 'Ammunition box with 12 category bullets "Shotgun".'),
('AMMO_SHOTGUN_LARGE', 'Shotgun ammo pack', 2.1, 100, 0, 1, 'Ammunition pack com 18 category bullets "Shotgun".'),
('AMMO_SMG', 'Submachine gun ammunition box', 1.75, 100, 0, 1, 'Ammunition pack com 45 category bullets "Sub-Machine gun".'),
('AMMO_SMG_LARGE', 'Submachine gun ammunition pack', 2.45, 100, 0, 1, 'Ammunition pack com 56 category bullets "Sub-Machine gun".'),
('AMMO_RIFLE', 'Machine gun ammunition box', 2.25, 100, 0, 1, 'Ammunition box with 45 category bullets "Machine gun".'),
('AMMO_RIFLE_LARGE', 'Machine gun ammunition pack', 3.05, 100, 0, 1, 'Ammunition box with 65 category bullets "Machine gun".'),
('AMMO_SNIPER', 'Sniper ammunition box', 1.65, 100, 0, 1, 'Ammunition pack com 10 category bullets "Sniper".'),
('AMMO_SNIPER_LARGE', 'Sniper ammo pack', 1.9, 100, 0, 1, 'Ammunition pack com 15 category bullets "Sniper".'),
('cash', 'Cash', 0, -1, 0, 1, '');